### ■ ニューラルネットワーク

In [13]:
import numpy as np

### ■ バックプロパゲーション

In [14]:
#------------------------------------------------------------------------------
# Neural Network
#------------------------------------------------------------------------------
class NeuralNetwork:

  def __init__(self, x_data, y_data, input_size, hidden_size, output_size):

    self.hidden_layer_weight = np.random.uniform(size=(input_size, hidden_size))
    self.output_layer_weight = np.random.uniform(size=(hidden_size, output_size))
    self.hidden_layer_bias = np.zeros((1, hidden_size))
    self.output_layer_bias = np.zeros((1, output_size))

    self.input_data = x_data
    self.hidden_data = None
    self.output_data = None
    self.true_label = y_data

  def func_sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def func_sigmoid_deriv(self, x):
    return x * (1 - x)

  def func_forward(self):

    ans = np.dot(self.input_data, self.hidden_layer_weight) + self.hidden_layer_bias
    self.hidden_data = self.func_sigmoid(ans)

    ans = np.dot(self.hidden_data, self.output_layer_weight) + self.output_layer_bias
    self.output_data = self.func_sigmoid(ans)
    
  def func_backward(self):

    learning_rate = 0.1

    loss_output = self.output_data - self.true_label
    deriv_output = loss_output * self.func_sigmoid_deriv(self.output_data)

    loss_hidden = deriv_output.dot(self.output_layer_weight.T)
    deriv_hidden = loss_hidden * self.func_sigmoid_deriv(self.hidden_data)

    self.output_layer_weight -= self.hidden_data.T.dot(deriv_output) * learning_rate
    self.output_layer_bias -= np.sum(deriv_output) * learning_rate

    self.hidden_layer_weight -= self.input_data.T.dot(deriv_hidden) * learning_rate
    self.hidden_layer_bias -= np.sum(deriv_hidden) * learning_rate

  def func_predict(self, x_test):             # 処理内容は Forward と同じ（引数はテストデータ）

    ans = np.dot(x_test, self.hidden_layer_weight) + self.hidden_layer_bias
    hidden_data = self.func_sigmoid(ans)

    ans = np.dot(hidden_data, self.output_layer_weight) + self.output_layer_bias
    output_data = self.func_sigmoid(ans)

    return output_data

  def func_train(self):
    epochs = 10000
    for _ in range(epochs):
      self.func_forward()
      self.func_backward()

#------------------------------------------------------------------------------
# Main
#------------------------------------------------------------------------------
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_data = np.array([[0], [1], [1], [0]])

neural_network = NeuralNetwork(x_data, y_data, 2, 2, 1)
neural_network.func_train()

print(f'== hidden_layer_weight ==')
print(f'{neural_network.hidden_layer_weight}')
print()
print(f'== hidden_layer_bias ==')
print(f'{neural_network.hidden_layer_bias}')
print()
print(f'== output_layer_weight ==')
print(f'{neural_network.output_layer_weight}')
print()
print(f'== output_layer_bias ==')
print(f'{neural_network.output_layer_bias}')
print()
print(f'== Predict ==')
print(f'(0, 0) : {neural_network.func_predict([0, 0])}')
print(f'(0, 1) : {neural_network.func_predict([0, 1])}')
print(f'(1, 0) : {neural_network.func_predict([1, 0])}')
print(f'(1, 1) : {neural_network.func_predict([1, 1])}')

#------------------------------------------------------------------------------
# Bonus
#------------------------------------------------------------------------------
print()
print(f'== Output Raw Array Data ==')
print(neural_network.output_data)

def softmax(x):
    exp_x = np.exp(x - np.max(x))     # オーバーフロー対策
    y = exp_x / np.sum(exp_x)
    return y

y = softmax(neural_network.output_data)

print()
print(f'== Applying the Softmax Function ==')
print(y)

== hidden_layer_weight ==
[[3.20213795 7.58939317]
 [3.20044131 7.58297132]]

== hidden_layer_bias ==
[[-4.73998845 -4.73998845]]

== output_layer_weight ==
[[-9.08728942]
 [ 7.7078119 ]]

== output_layer_bias ==
[[-2.81382101]]

== Predict ==
(0, 0) : [[0.05594732]]
(0, 1) : [[0.94608316]]
(1, 0) : [[0.94609969]]
(1, 1) : [[0.06037647]]

== Output Raw Array Data ==
[[0.05595193]
 [0.94607827]
 [0.9460948 ]
 [0.0603822 ]]

== Applying the Softmax Function ==
[[0.14544703]
 [0.35422714]
 [0.35423299]
 [0.14609283]]
